### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by durtal** [phillc73/pinhooker#2]
Hi Phill,

I tried installing this package tonight (looks to have great potential, so thanks!), but getting an error:

```
* installing *source* package 'pinhooker' ...
** R
Error in parse(outFile) : 
  C:/Users/**********/AppData/Local/Temp/RtmpWWpHaQ/devtools5c46a42477d/phillc73-pinhooker-94c3782/R/getArqana.R:102:16: unexpected input
101:     saleData$Nom[saleData$Nom == "INCONNU"] <- "UNKNOWN"
102:     saleData$PÃ¨
                    ^
ERROR: unable to collate and parse R files for package 'pinhooker'
```

Obviously the way some of the variables are parsed (at least in Windows) causes issues.

I created a fork, to try fix this and send over a PR, but for some reason couldn't fix it.  I thought it might be a simple case of renaming the variables after reading in the data from the url, moving [these lines](https://github.com/durtal/pinhooker/blob/master/R/getArqana.R#L117-L123) - and then obviously changing the variables used in the **Translate French To English** section of code.  Will probably take another look at it tomorrow, but thought I'd open an issue just so you're aware.

Session Info

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] httr_1.1.0     R6_2.1.2       tools_3.2.3    curl_0.9.5     memoise_0.2.1  digest_0.6.9   devtools_1.9.1
```

**Comment by phillc73** [comment]
Thanks for sorting this out Tom. This all looked fine originally on my Linux machine, so probably something to do with Windows and fonts/language.  I must remember to test better on Windows.
